import { PERMISSIONS } from "./permissions.js";

export const ROLES = Object.freeze({
  SUPER_ADMIN: "super_admin",
  COMPANY_ADMIN: "company_admin",
  HR: "hr",
  SUPPORT: "support",
  EMPLOYEE: "employee",
});

export const USER_STATUS = Object.freeze({
  ACTIVE: "active",
  INACTIVE: "inactive",
  BLOCKED: "blocked",
});

export const COMPANY_STATUS = Object.freeze({
  ACTIVE: "active",
  INACTIVE: "inactive",
  SUSPENDED: "suspended",
  TRIAL: "trial",
});

export const SUBSCRIPTION_STATUS = Object.freeze({
  TRIAL: "trial",
  ACTIVE: "active",
  EXPIRED: "expired",
  CANCELLED: "cancelled",
});

export const ROLE_PERMISSIONS = Object.freeze({
  super_admin: [
    PERMISSIONS.AUTH_ME,
    PERMISSIONS.PROFILE_READ,
    PERMISSIONS.PROFILE_UPDATE,

    PERMISSIONS.COMPANY_CREATE,
    PERMISSIONS.COMPANY_READ,
    PERMISSIONS.COMPANY_UPDATE,
    PERMISSIONS.COMPANY_DELETE,
    PERMISSIONS.COMPANY_STATUS_UPDATE,
    PERMISSIONS.COMPANY_ADMIN_CREATE,

    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_DELETE,
    PERMISSIONS.USER_BLOCK,
    PERMISSIONS.USER_UNBLOCK,
    PERMISSIONS.USER_RESET_PASSWORD,
    PERMISSIONS.USER_ASSIGN_ROLE,
    PERMISSIONS.USER_ASSIGN_PERMISSION,

    PERMISSIONS.PLATFORM_DASHBOARD_READ,
    PERMISSIONS.PLATFORM_SETTING_MANAGE,
  ],

  company_admin: [
    PERMISSIONS.AUTH_ME,
    PERMISSIONS.PROFILE_READ,
    PERMISSIONS.PROFILE_UPDATE,

    PERMISSIONS.COMPANY_PROFILE_READ,
    PERMISSIONS.COMPANY_PROFILE_UPDATE,

    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_BLOCK,
    PERMISSIONS.USER_UNBLOCK,
    PERMISSIONS.USER_RESET_PASSWORD,

    PERMISSIONS.HR_CREATE,
    PERMISSIONS.HR_READ,
    PERMISSIONS.HR_UPDATE,

    PERMISSIONS.SUPPORT_READ,
    PERMISSIONS.EMPLOYEE_READ,

    PERMISSIONS.ATTENDANCE_MANAGE,
    PERMISSIONS.LEAVE_MANAGE,
    PERMISSIONS.PAYROLL_MANAGE,

    PERMISSIONS.REPORT_READ,
  ],

  hr: [
    PERMISSIONS.AUTH_ME,
    PERMISSIONS.PROFILE_READ,
    PERMISSIONS.PROFILE_UPDATE,

    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_BLOCK,
    PERMISSIONS.USER_UNBLOCK,
    PERMISSIONS.USER_RESET_PASSWORD,

    PERMISSIONS.SUPPORT_CREATE,
    PERMISSIONS.SUPPORT_READ,
    PERMISSIONS.SUPPORT_UPDATE,

    PERMISSIONS.EMPLOYEE_CREATE,
    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.EMPLOYEE_UPDATE,
    PERMISSIONS.EMPLOYEE_DELETE,

    PERMISSIONS.ATTENDANCE_MANAGE,
    PERMISSIONS.LEAVE_MANAGE,
    PERMISSIONS.PAYROLL_READ,
    PERMISSIONS.REPORT_READ,
  ],

  support: [
    PERMISSIONS.AUTH_ME,
    PERMISSIONS.PROFILE_READ,
    PERMISSIONS.PROFILE_UPDATE,

    PERMISSIONS.EMPLOYEE_READ,

    PERMISSIONS.TICKET_CREATE,
    PERMISSIONS.TICKET_READ,
    PERMISSIONS.TICKET_UPDATE,

    PERMISSIONS.NOTIFICATION_READ,
  ],

  employee: [
    PERMISSIONS.AUTH_ME,
    PERMISSIONS.PROFILE_READ,
    PERMISSIONS.PROFILE_UPDATE,

    PERMISSIONS.ATTENDANCE_SELF,
    PERMISSIONS.LEAVE_SELF,

    PERMISSIONS.TICKET_CREATE,
    PERMISSIONS.TICKET_SELF,

    PERMISSIONS.NOTIFICATION_READ,
  ],
});